services:
  - type: web
    name: lightfm-recommendation-api
    env: python
    buildCommand: python -m pip install --upgrade pip setuptools wheel && python -m pip install --no-use-pep517 lightfm && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    disk:
      name: model-cache
      mountPath: /app/model_cache
      sizeGB: 1
